# Generated by Django 5.2.7 on 2025-10-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="agent",
            name="prompt",
            field=models.TextField(),
        ),
    ]
