version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: agent_platform_admin
      POSTGRES_PASSWORD: some_secure_password_123
      POSTGRES_DB: agent_platform
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U agent_platform_admin -d agent_platform"]
      interval: 5s
      timeout: 5s
      retries: 5

  agent_platform_app:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    container_name: agent_platform_app
    volumes:
      - ..:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DEBUG=1
      - DB_NAME=agent_platform
      - DB_USER=agent_platform_admin
      - DB_PASSWORD=some_secure_password_123
      - DB_HOST=db
      - DB_PORT=5432

volumes:
  postgres_data:
